dataset: ROCOv2
dataset_url: eltorio/ROCOv2-radiology
seed: 42
save_raw_data: False
raw_train_data_path: ./ROCOv2_raw_train_data.pkl
raw_val_data_path: ./ROCOv2_raw_val_data.pkl
raw_test_data_path: ./ROCOv2_raw_test_data.pkl


use_saved_dataset: False
dataset_storage_train: ./train_dataloader.pkl
dataset_storage_val: ./val_dataloader.pkl
dataset_storage_test: ./test_dataloader.pkl

apply_transformations_in_getitem: True

transformations:
  image:
    - type: Resize
      params:
        size: [224, 224]
    - type: Normalize
      params:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
  text:
    - type: lowercase
      params: {}
    - type: remove_punctuation
      params: {}



